---
version: '3.9'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.4.3-python3.9
  user: "${AIRFLOW_UID}:0"
  env_file: 
    - ./airflow/airflow.env
  volumes:
    - ./airflow/airflow2.4.3.cfg:/opt/airflow/airflow.cfg  # custom cfg with run_id (incl timestamp) removed from log_filename_template.
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./outputs:/opt/airflow/outputs

x-airflow-depends-on:
  &airflow-depends-on
  postgres:
    condition: service_healthy
  airflow-init:
    condition: service_completed_successfully

services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    env_file:
      - ./airflow/airflow.env

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: on-failure
    expose:
      - 8793
    depends_on:
      <<: *airflow-depends-on

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    restart: always
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
    depends_on:
      <<: *airflow-depends-on
  
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    depends_on:
      - postgres
  